export const START_TIMER = 'START_TIMER';
export const STOP_TIMER = 'STOP_TIMER';
export const RESET_TIMER = 'RESET_TIMER';

export const START_ALL_FILTER_TIMER = 'START_ALL_FILTER_TIMER';
export const STOP_ALL_FILTER_TIMER = 'STOP_ALL_FILTER_TIMER';
export const LAP_ALL_FILTER_TIMER = 'LAP_ALL_FILTER_TIMER';
export const RESET_ALL_FILTER_TIMER = 'RESET_ALL_FILTER_TIMER';


export const ADD_ATHELETE = 'ADD_ATHELETE';
export const DELETE_ATHLETE= 'DELETE_ATHLETE';
export const SET_GROUP_FILTER= 'SET_GROUP_FILTER';
export const UPDATE_ATHLETE_PRESENT= 'UPDATE_ATHLETE_PRESENT';
export const UPDATE_ATHLETE_GROUP= 'UPDATE_ATHLETE_GROUP';
export const ADD_ATHLETE_LAP='ADD_ATHLETE_LAP';

export const ADD_PROGRAM_STEP='ADD_PROGRAM_STEP';
export const DELETE_PROGRAM_STEP='DELETE_PROGRAM_STEP';
export const UPDATE_PROGRAM_STEP_DURATION='UPDATE_PROGRAM_STEP_DURATION';
export const UPDATE_PROGRAM_STEP_TYPE='UPDATE_PROGRAM_STEP_TYPE';

export const SHOW_NOTIFICATION='SHOW_NOTIFICATION';
export const HIDE_NOTIFICATION='HIDE_NOTIFICATION';

export const NEXT_STEP='NEXT_STEP';

export const START_INTERVAL='START_INTERVAL';
export const PAUSE_INTERVAL='PAUSE_INTERVAL';
export const UPDATE_ATHLETE_ORDER='UPDATE_ATHLETE_ORDER';
export const SET_OFFSET='SET_OFFSET';




