language: node_js
sudo: required
node_js:
- '7'
services:
- docker
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@^5.3.0
install:
- npm install
- npm run build
script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -t $REPO:$TAG .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
- docker push $REPO
deploy:
  provider: releases
  api_key:
    secure: XtPXmMfl0xaedXcUqHLdl9qBxAY5YH6pMvAvt2cRLYd/rBsV2gTpIrIPRI6tnbh6WSB4KlwnI8F9Q+w4Y9WEnuEVmYeDkJCJplg9P1m5nsTgT0RoIlHfERrOyqLh0YIC6reRiAFRcusMXcMa7ONVMgFrG/i4DGlbGOmsGAn/5NRp2LU7HS96ITwsdmmJQS4HIFj6wJvngHMdIYUJxl2qaYqNKjuyZgZND1aKwYbm1w1NetNFA1IL40j59+N/SL0qbVvB/eNzFuKwKd5cIOXqO8T/LeZkcuWdpj8wnbL9wnWfbchyOSt8R0Lw4LjbtKzGsydMNtJG/ySbdvrbs9CIdYPNsVQ+cJjAyNQJfnUZCE9CzzCB280/UhVIrOmyruZaecTosmFmImNwaqRw+anNOO0lU+/HSM+JV7glUQB+9wG5FhmvWx98MYlNXb0T2tdvHPa9t7NNpYYyNIF206cCTX00W66cpLbQU+Smu5I1fmsZdpy6kcH26nuumXyd7j0IZXy4AcG27QwReRIBmyg+TfPLkCj+bhCxTUEb9GYGVIvXMnvu35BgDnDS6P5aWEiHvUln3zvopv7gtoq+dnkAioQ3t3Uo6XL2vxodOUcP7mLcY1pE2kDussI6TqgwnqlPgb65Vtig8VWUu3r7p0+FI3lSRUdlPf3DqDqfDSy0y9Y=
  file: dist/chrono.zip
  skip_cleanup: true
  on:
    tags: true
    repo: "$REPO"
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=$DOCKER_USER/chrono
  - secure: re85i5JIgod5mNJiBbPPH7Olgp2xdcO8frWqmRmrwTyQ++Mbmq+ENwnwZY7zsgTtOZQlX0i6L/pSW14vhd9Qn4ds/59cm5FR/3sB0SDXx6GOtfm6DHxzpASMbnZcadpweDOeT4yDRBEoDtxotfpWcCEgwm+VzkX9VRDhW92yCkegj87f6ILOdpG1XqBQSgvSxYTSWOcYLy6eOyGdo8HQl1/weiwnUM/APJ+IzoDuqST0ESbhh8QQ3PVVKHD/TjvpN7aWdpb7MuRDQOkOR5h/BsP+NHuGe28d1nEw4tv7ATW+aJPxr3vDoRs9GRMrAgPVRVy4kmxQOit1GwUsKdyjKUWB2ZIc3+cUHeM/YotIq5Fe/axA3xr3yfhIvBBrk8x7QP7TE3m8ee04wel/SHq4+PM2sshxGsu32PnJrwaKn9RK1hTsu5FHwg3UyJZVSKvJBnBj8NgKPu1QOExAn/Ou0o1iNNipDVpOAVWjBz5LPh+6MB7ULEHoyViZEiuui+NBBXFjPPF5vk+59a6snSQOthzLIMX1kuZTqI1MsEGBcJqvyl4pcz9ZF5P01GPfw+8fV61Q1Mm5ec6gdbMcTqShKiXmsnXClvR13Pyf92Hvt3WEMvpszq7362LKHamXTPenCXy1v176z/CgoWkBXw+pUinIqtbE6Y0b8CRZFGfABjQ=
  - secure: jxpQzlCLfbjPEKWO6oIu3tZ72cUtSccZuVA5fIATRBlyT0V23V0QrRw4AnETgcqei/nree++uOxy77h7qudIdZnp/GO6wB94rvhxDHPYZgoEa2j3yXRxayndVc0s5XHFaEFkYxoW5A0r/cyr9rk6zuqqrTMj5NtfEy/9bbXP/1Oo81AlnsNuvWSwt7EliOzX+Uvmg9YYslk8XgXE1mrKFdyLCdmRxgXkh93oyg2XyOCatF8/ihQiRr3+Na9Y5KCWONRLmjJxvEdj7A5dwePqX0y7RMzFnDkbj1YLmiUk7UpgAsfKu7sKt08ji9IecN6RMXR1NMLzEGGTbe+VDHmC1PYKrxRNXN5ARwv+jN/KZZgMI78EU2QzsmTT0M4CIlL923qkLX9ahQ7YgGYORyApmpbxswce+VLagTjmm4wYaIYx9r4/e5CO6d9fp2cgsWyC2ZpIZmkNqkyfqQVr9cCoYjspU9NuHydyGi4jAX0ToIQkEHyHHyNVp3dDWFX2svV7DGArVx852wmRw1hssUdNyKA5yO6tOuOPjImS9mwOu//GVid7CsFSsoaxXLJXkUo+qvCIjR9tO9xTGwVOmIQZ8jc1VXPET4/KlmauT158AGTJjyHnr8MZvwkm7xNZxWuN9HOvRQaxaFsRxQD5YoGgtYJW8m1cDif5S+tk+7KzEG8=
