language: node_js
sudo: required
node_js:
- '7'
services:
- docker
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@^5.3.0
install:
- npm install
- npm run build
script:
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH;
  fi`
- docker build -t $REPO:$TAG .
after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
- docker tag $REPO:$COMMIT $REPO:$TAG
- docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
- docker push $REPO
deploy:
  provider: releases
  api_key:
    secure: XtPXmMfl0xaedXcUqHLdl9qBxAY5YH6pMvAvt2cRLYd/rBsV2gTpIrIPRI6tnbh6WSB4KlwnI8F9Q+w4Y9WEnuEVmYeDkJCJplg9P1m5nsTgT0RoIlHfERrOyqLh0YIC6reRiAFRcusMXcMa7ONVMgFrG/i4DGlbGOmsGAn/5NRp2LU7HS96ITwsdmmJQS4HIFj6wJvngHMdIYUJxl2qaYqNKjuyZgZND1aKwYbm1w1NetNFA1IL40j59+N/SL0qbVvB/eNzFuKwKd5cIOXqO8T/LeZkcuWdpj8wnbL9wnWfbchyOSt8R0Lw4LjbtKzGsydMNtJG/ySbdvrbs9CIdYPNsVQ+cJjAyNQJfnUZCE9CzzCB280/UhVIrOmyruZaecTosmFmImNwaqRw+anNOO0lU+/HSM+JV7glUQB+9wG5FhmvWx98MYlNXb0T2tdvHPa9t7NNpYYyNIF206cCTX00W66cpLbQU+Smu5I1fmsZdpy6kcH26nuumXyd7j0IZXy4AcG27QwReRIBmyg+TfPLkCj+bhCxTUEb9GYGVIvXMnvu35BgDnDS6P5aWEiHvUln3zvopv7gtoq+dnkAioQ3t3Uo6XL2vxodOUcP7mLcY1pE2kDussI6TqgwnqlPgb65Vtig8VWUu3r7p0+FI3lSRUdlPf3DqDqfDSy0y9Y=
  file: dist/chrono.zip
  skip_cleanup: true
  on:
    tags: true
    repo: "$REPO"
env:
  global:
  - secure: B8Z5pvFYnGMQRtv9hiJqwM8KAKfHiriMvjF3gmeEs0gmCSVKuubzxxqT435CGfcBvVIyiXwNo2//87mG/Hp2U5mokilk8aplVh19Y1VlfQXZmdYRxc9ac5Kxe5qV4aQIyOw/jNSfG3EisN4DmfZc2ZbLoECDo/+Oywb/7QN3QyivZ/ARPwbexxrEvEBXDPft1F9/9Ut3hfnBN7bN8zmXr6idAj3Jt/boM9ley4wXNGIsoGstPZ3+v1cc418fGiAZ+I6VwNI3kOT+ZQ4b+QoipivOwMrbWBN3MgTSI8qSw3DQxuqn3hCPBM0Rqa3xGiKa0EBGAkiflTpJj3V5UPDnuDeeqInrWj6CoErQALAZMYxrjmZJ4FEiVZcFhsqv4N5h8q8DmC49LEN1YOGilKXq77Y6v9W59kZouf0oGe8ak/sykJVvpm24X8eahnS6CLM6CvVMgFZwUnuAoe+8w84Ikr82WgsaagC8hT3S9BsD36QwOpTAza4LDODQNgxIJY1K+Kdp7vHcrqSJvUgXo3ZIu5+JcR3gizvnxABsY2dPQI4xEtguThAgCEesg/GR0ZG23Gq0XIK4R3Vv4ghMiLP+FZQBDRbihohzlIAWC1L5/ACupQEt4V5WHC5FgEH+BYuFTD1o0nWR2UhsiJ/AXpGxayTQdUYeB9Zt1I1zY/mBvps=
  - secure: hmVbuNH4ZNx++dECBg3e9bJldXFk/bdPxcWESHAa8iNM6k4SzP1K3V1mvCoHk91XNUUFDUkYfotR/rPlW0QmjJ8rErQpMqKaXsEzI0wQgl9XViHekuEE3OCjNRBMYVhFwM0Ms84OnRwpWi++qYISwG33fGYdAk3096ytq0vnPMLy3Rvh57ruJWomdAqx61dmRh3pKrIT+ompqQxS426xQbi104kkE0/pLiVdyLwtB+qOJ3Bnos0Lr8t5aV5NoQpOTiyKN0GI8rcz9yeviVV3XYy0jKjaA4abQENVPZYgT1guYv4DJh4CItjVMusOORoqCLHz5m6/vgWWDU0kjUR43yZP7xhfFfkEeZ4zAn2gWupj2CZoMN8xp4xKYXgr2hw2/OkiEAmxOKWLN0G5rrTv3bGFk5hXxmIc0oMot9rTJcy+aJNUhT9BpdCe+RpxroYdKJoxwWhmYcxrb3x+sZnnJ5XugIUD8HrftKV/4g9zvulVoLU6ZnkNHd8ga10eDoTPzeC0Smli5uIGj6yO6UvR7ArrGty/w27QVxML+KoyVMHKmZ3AVwGziBgvbW9ZPLKfnyjuGhMVB4CyDc87pS4W8jEHNpVxuHB/q4AK5zJFqLHo4sZIixPW+kaGBa1wXg2zleQg8EQVTidyO/YTguY2ehtTAv3Q33oYurp3Y2wWbcc=
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=$DOCKER_USER/chrono
