language: node_js
node_js:
  - '7'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
before_install:
- npm i -g npm@^5.3.0
install:
- npm install
- npm run build
before_script:
- npm install -g codecov
script:
- npm run test
- codecov
