language: node_js
sudo: required
node_js:
- '7'
services:
- docker
cache:
  directories:
  - node_modules
before_install:
- npm i -g npm@^5.3.0
install:
- npm install
- npm run build
script:
 - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
 - docker build -t $REPO:$TAG .
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then
  docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  docker tag $REPO:$COMMIT $REPO:$TAG
  docker tag $REPO:$COMMIT $REPO:$TRAVIS_BUILD_NUMBER
  docker push $REPO
  fi
deploy:
  provider: releases
  api_key:
    secure: XtPXmMfl0xaedXcUqHLdl9qBxAY5YH6pMvAvt2cRLYd/rBsV2gTpIrIPRI6tnbh6WSB4KlwnI8F9Q+w4Y9WEnuEVmYeDkJCJplg9P1m5nsTgT0RoIlHfERrOyqLh0YIC6reRiAFRcusMXcMa7ONVMgFrG/i4DGlbGOmsGAn/5NRp2LU7HS96ITwsdmmJQS4HIFj6wJvngHMdIYUJxl2qaYqNKjuyZgZND1aKwYbm1w1NetNFA1IL40j59+N/SL0qbVvB/eNzFuKwKd5cIOXqO8T/LeZkcuWdpj8wnbL9wnWfbchyOSt8R0Lw4LjbtKzGsydMNtJG/ySbdvrbs9CIdYPNsVQ+cJjAyNQJfnUZCE9CzzCB280/UhVIrOmyruZaecTosmFmImNwaqRw+anNOO0lU+/HSM+JV7glUQB+9wG5FhmvWx98MYlNXb0T2tdvHPa9t7NNpYYyNIF206cCTX00W66cpLbQU+Smu5I1fmsZdpy6kcH26nuumXyd7j0IZXy4AcG27QwReRIBmyg+TfPLkCj+bhCxTUEb9GYGVIvXMnvu35BgDnDS6P5aWEiHvUln3zvopv7gtoq+dnkAioQ3t3Uo6XL2vxodOUcP7mLcY1pE2kDussI6TqgwnqlPgb65Vtig8VWUu3r7p0+FI3lSRUdlPf3DqDqfDSy0y9Y=
  file: dist/home-automation-webapp.zip
  skip_cleanup: true
  on:
    tags: true
    repo: jluccisano/home-automation-webapp
env:
  global:
  - secure: BwAUiOrQxFzTJav4drKepf88MU8DoKuj3GKkNNw/isRktDU4sd0NhC2CyG0aPMyXAaoTBqM349SEVMTFLGiCkOscWITpFEKQ01deUCoarA7flzsFxfHbrVlwVUlpu8lNlhnLprvYr6ArAUvdsMdM2pxa7bxa3JEn2fmSJDAy4XzzRVN2FNPE5KxFkxYotrqsW8S+yu5kEWhijXmfjJU1bQu3LEmk5KJ8ZcyNZW0KULspj4HaIezI/z6bU4ZABrD3w75Aek8sXWdnZF7ogIhGjT0UcQHSKPXvn1YGpFwHFHCa74WH531mXM1t34W9QCRNSdFfXtgVNkRjn81mpIkcZNlfTbOvrw+8eyKmZc9eSjFfS7LFcDApIrT6pHI7LIA+cGjj8U6qp8QAvYC1oC3IwjI75cGT8K9so46wNMxd1xPhYzHRtfU2bSyN87AdbzR8VVtGkMktcp0eXnuGk/32VtLZoNXyq1equZ3e8/U34rZdMjsCt2baSQqh+GlZD8yLapj6cTwxg20o43MBpe+7tVK8qMofsEPe2NmawZyCmnJpQfPYfLKI+S+Xyo/xn0uj8Wg/221rCTwej6mCQOaTPyhGGVf8Qh/F8sM0tqZbkdJSzVpoPFwIDZPrwNMnCcY2BQIraT1pd6Rjc5WihOONalF+q2awpWznoiR3DQHsHH0=
  - secure: Z9pfKHdMhoxi1oxB0U8g+9HZt7Gp4/hX2RbDI/COjdvgApY+yIBCIZIfkQw1KbBolxpFO5NZbP5QlPeYVuoqSIoX+LOjVv/0VU9UmT+xmw4YO48d0fd5UNJRZydBMO6UnVZMMifyuqmilOLVZNyyR3HiV2ROqLo5dDFbfBlIDgKjPF8sQt9RNtzxH1cQmXg+iKqIluRWT/ONDFuEappqNPl0jweQyiHlzi1RdA4S5YjGznoj/4BTB8iT4seouUYgVdsygeKKSWOCgssj1/HaZTx97V0kBKlcjsixAjCPGOEtBQMXCEbwjvwSkp/L3rP04UjrTbdpFwQpqHeuTHODX14khAI1bjcShMqnF6AL9O1fI9Uxly6BEeSk3U1aUh90I2D9trVMlO5GnYItt0H5HQTuoU6GOMdOcN/1btxJvhDWOwojjT3noUj8jyReMj+0E6iX1qJom/gnTrATct606AZx9pHU5/ZEv/bdg8yj/kIviVjpNZSTYz70i74QOGcrfU1BQ4nrewXZ7cBB4lsHzKCLjjRAy0wxwQlN3THep4JcF2uqls2hHOk33JLinVHyu6Pz2kxw0IghstrY3VzSKpgLPK0V+BA7DLvswtytvZtNmbl2Czgh7F0lt9+uPR9smFN6meSqENFvLJq13+F9sUMb5AiTKdrnf2BV/c6rJCY=
  - secure: JORgvCrUnH2BVuXC7JhXs6Hxmo/BOI130nGLMwxX4280AbvhUX+KNEKf8kc9Rmsm0lEdNTp6a1Z9pkRmnddK7xTj8vzp79pOZzOdXoS8znZRsM2seCNPugi2eRyB2eFzsbq6jq4Y5mbLoop+vBtQTUkjenWIgvq87JOsbq0bgLN0rKoT1XzTp+4bYqIjHnKtm0Du3WeDerxr63pjmTLi44riW1KhhiQkFoHBSfVeQNE4yJ7cgazBBiqlKm4Y6CVLKCgwbZejuurtJXRBXhaPNOoYBEu9mvV8YiaO5Q1iTP+f59kWyCKaNEOE0OkBUgp2PjrNAvO2awOpkXZeuvskkMCQG4G6S6lEPN7cD2ZozTfwo3k8o/JdZ2m4fpTxGuDNvd1c3mlowOCkzclDOvwSO5sr5CCbRbmF67x5RNo3Sqdx2FU11K9ijDT9tGenuk48bjT4ZN+RTGXHxtbP3FTYNb34q1pyt1MzCwn9ZxqABrjZtVs1/m3cImIUfaEN/3rLRmgu4prcQuaJJqT93Hs7M+ARJ2n2LthcVTyVeS7+5ZTSrTSMIMEdLEeTWyIr7ZsFpotZ1caKRg2FGVnwcBkiyLO+v3BjT1fn+0yyy3ynRJIxIea0jc4WqxXWwEIpa9KycdkGfBt2XkYZ6lhHVFH/73c7NMdSVsTRITelJsF2jxE=
  - COMMIT=${TRAVIS_COMMIT::8}
  - REPO=$DOCKER_USERNAME/home-automation-webapp
